# Site settings
title: REND3D
description: Archviz + Digitalization
baseurl: "/rend3d" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
logo: 'assets/images/logo.png'

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://facebook.com/rend3dart
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/neobrutalstudio
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

theme: jekyll-theme-slate
